"""Scope compilation, including one pass through graphify's own ignore matcher."""

from __future__ import annotations

from pathlib import Path

from ef import scoping


def source(path: str, paths: list[str] | None = None, kind: str = "git") -> dict:
    entry = {"name": path, "path": path, "origin": {"type": kind}}
    if paths:
        entry["paths"] = paths
    return entry


def test_metadata_is_excluded_from_its_own_corpus() -> None:
    """A skill teaching an agent to query a corpus must not become a node in it."""
    text = scoping.compile_ignore([])
    assert "/expert.json" in text
    assert "/SKILL.md" in text
    assert "/.graphifyignore" in text


def test_the_file_is_marked_as_generated() -> None:
    assert scoping.compile_ignore([]).startswith("# Generated by ef")


def test_an_unscoped_git_source_adds_no_rules() -> None:
    text = scoping.compile_ignore([source("repos/acme/lib")])
    assert "repos/acme/lib" not in text


def test_a_nested_scope_re_includes_every_ancestor() -> None:
    """gitignore's parent-exclusion rule: a negation cannot rescue a file under an
    excluded ancestor, so each directory on the way down is re-included."""
    text = scoping.compile_ignore([source("repos/acme/lib", ["content/docs"])])
    lines = text.splitlines()

    assert "/repos/acme/lib/*" in lines
    assert "!/repos/acme/lib/content" in lines
    assert "!/repos/acme/lib/content/docs" in lines
    assert "!/repos/acme/lib/content/docs/**" in lines
    assert lines.index("/repos/acme/lib/*") < lines.index("!/repos/acme/lib/content")


def test_several_scopes_on_one_source() -> None:
    text = scoping.compile_ignore([source("repos/acme/lib", ["docs", "guides"])])
    assert "!/repos/acme/lib/docs/**" in text
    assert "!/repos/acme/lib/guides/**" in text


def test_a_non_git_source_is_never_scoped() -> None:
    text = scoping.compile_ignore([source("raw/paper.pdf", ["nonsense"], kind="fetch")])
    assert "raw/paper.pdf" not in text


def test_regeneration_is_idempotent(tmp_path: Path) -> None:
    sources = [source("repos/acme/lib", ["content/docs"])]
    first = scoping.write_ignore(tmp_path, sources).read_text(encoding="utf-8")
    second = scoping.write_ignore(tmp_path, sources).read_text(encoding="utf-8")
    assert first == second


def test_credentials_are_excluded_from_the_corpus() -> None:
    """Extraction runs --no-gitignore, so the clone's own rules no longer guard these."""
    text = scoping.compile_ignore([])
    for pattern in (".env", ".env.*", "*.pem", "id_rsa", ".npmrc", ".netrc"):
        assert pattern in text.splitlines()


def test_a_stray_credential_never_reaches_the_matcher(tmp_path: Path) -> None:
    """The guard has to hold under graphify's real matcher, not just as text."""
    from graphify.detect import _is_ignored, _load_graphifyignore

    pack = (tmp_path / "pack").resolve()
    clone = pack / "repos/acme/lib"
    (clone / "certs").mkdir(parents=True)
    (clone / "src").mkdir()

    secrets = [clone / ".env", clone / ".env.production", clone / "certs/server.pem"]
    code = clone / "src/index.ts"
    for path in [*secrets, code]:
        path.write_text("x", encoding="utf-8")

    scoping.write_ignore(pack, [source("repos/acme/lib")])
    patterns = _load_graphifyignore(pack, gitignore=False)

    for secret in secrets:
        assert _is_ignored(secret, pack, patterns), f"{secret.name} must never be extracted"
    assert not _is_ignored(code, pack, patterns), "ordinary source must still be scanned"


def test_the_generated_file_survives_graphifys_own_matcher(tmp_path: Path) -> None:
    """The one place worth crossing the boundary: the semantics are subtle and borrowed."""
    from graphify.detect import _is_ignored, _load_graphifyignore

    pack = tmp_path / "pack"
    clone = pack / "repos/acme/lib"
    wanted = clone / "content/docs"
    wanted.mkdir(parents=True)
    (clone / "src").mkdir()

    keep = wanted / "guide.md"
    keep.write_text("# guide\n", encoding="utf-8")
    drop = clone / "src/app.ts"
    drop.write_text("export {}\n", encoding="utf-8")
    metadata = pack / "SKILL.md"
    metadata.write_text("# skill\n", encoding="utf-8")

    scoping.write_ignore(pack, [source("repos/acme/lib", ["content/docs"])])
    patterns = _load_graphifyignore(pack, gitignore=False)

    assert not _is_ignored(keep, pack, patterns), "the wanted subtree must survive"
    assert _is_ignored(drop, pack, patterns), "application code outside the scope must be dropped"
    assert _is_ignored(metadata, pack, patterns), "the pack's own metadata must be dropped"
