"""Compile per-source path scopes into the pack's one generated ignore file."""

from __future__ import annotations

from pathlib import Path

from .workspace import IGNORE_NAME, MANIFEST_NAME, SKILL_NAME

HEADER = (
    "# Generated by ef on every build — do not edit; your changes will be lost.\n"
    "# Scopes each git source to its manifest `paths`, and keeps the pack's own\n"
    "# metadata out of the corpus it describes.\n"
)


def _scope_rules(source_path: str, paths: list[str]) -> list[str]:
    """Exclude a clone's contents, then re-include the wanted subtrees.

    Written against the clone's *contents* rather than the clone itself, because
    gitignore's parent-exclusion rule means a negation cannot re-include a file
    whose ancestor directory is excluded. Each ancestor of a wanted subtree is
    therefore re-included explicitly.
    """
    base = source_path.strip("/")
    rules = [f"/{base}/*"]
    for wanted in paths:
        parts = [p for p in wanted.strip("/").split("/") if p]
        if not parts:
            continue
        prefix = base
        for part in parts:
            prefix = f"{prefix}/{part}"
            rules.append(f"!/{prefix}")
        rules.append(f"!/{prefix}/**")
    return rules


def compile_ignore(sources: list[dict]) -> str:
    """Render the generated ignore file for a pack's sources."""
    lines = [HEADER.rstrip("\n"), "", "# The pack's own metadata is not corpus content."]
    lines += [f"/{MANIFEST_NAME}", f"/{SKILL_NAME}", f"/{IGNORE_NAME}"]

    for source in sources:
        paths = source.get("paths")
        if not paths or source.get("origin", {}).get("type") != "git":
            continue
        lines += ["", f"# {source.get('name', source['path'])}: scoped to {', '.join(paths)}"]
        lines += _scope_rules(source["path"], list(paths))

    return "\n".join(lines) + "\n"


def write_ignore(pack: Path, sources: list[dict]) -> Path:
    target = pack / IGNORE_NAME
    target.write_text(compile_ignore(sources), encoding="utf-8")
    return target
